language: 'en'
player-language: true

ingame:
  show-death-screen: false
  fall-damage: false
  enable-invites: true
  enable-parties: true
  enable-spectating: true
  enable-afk: true
  block:
    break: false
    place: false
  player:
    allow-gm: false
    allow-fly: false
    allow-hunger: false
  teleport:
    allow: false
    leave-on-tp: true
  scoreboard:
    title: "&bPvP&7 - Stats"
    lines:
      - ' '
      - '&9{NAME}'
      - '&7Arena: &8{PVPARENA}'
      - ' '
      - '&7Kills: &a{PVPKILLS}'
      - '&7Deaths: &c{PVPDEATHS}'
  commands:
    block: true
    override:
      op: true
      perm: true
    whitelist:
      - 'pvp'
      - 'help'
      - 'msg'
      - 'w*'
  spectating:
    gamemode: SPECTATOR
    allow-fly: true
  afk:
    idle-period: 60
    notify-damager: true
    indicators:
      move: true
      interact: true
      chat: false
gadgets:
  grenades:
    enable: true
    item: EGG
    settings:
      throw-multiplier: 3.0
      infinity: true
      power: 10.0
      fire: false
      block-destroy: false
kits:
   default:
      cost: 0
      items:
         - "0;diamond_sword;1;&bPvP&7-Sword;DAMAGE_ALL:2,DURABILITY:3"
         - "1;bow;1;&bPvP&7-Bow;ARROW_INFINITE:1,DURABILITY:3"
         - "2;fishing_rod;1;;DURABILITY:3"
         - "4;golden_apple;3"
         - "9;arrow"
         - "helmet;diamond_helmet;1;;DURABILITY:3"
         - "plate;diamond_chestplate;1;;DURABILITY:3"
         - "leggings;diamond_leggings;1;;DURABILITY:3"
         - "boots;diamond_boots;1;;DURABILITY:3"