language: 'en'

ingame:
  show-death-screen: false
  fall-damage: false
  enable-invites: true
  block:
    break: false
    place: false
  player:
    allow-gm: false
    allow-fly: false
    allow-hunger: false
  teleport:
    allow: false
    leave-on-tp: true
  scoreboard:
    title: "&bPvP&7 - Stats"
    lines:
      - ""

kits:
   default:
      cost: 0
      items:
         - "0;diamond_sword;1;&bPvP&7-Sword;DAMAGE_ALL:2,DURABILITY:3"
         - "1;bow;1;&bPvP&7-Bow;ARROW_INFINITE:1,DURABILITY:3"
         - "2;fishing_rod;1;;DURABILITY:3"
         - "4;golden_apple;3"
         - "9;arrow"
         - "helmet;diamond_helmet;1;;DURABILITY:3"
         - "plate;diamond_chestplate;1;;DURABILITY:3"
         - "leggings;diamond_leggings;1;;DURABILITY:3"
         - "boots;diamond_boots;1;;DURABILITY:3"