name: PvP
version: '1.0-b1'
author: Lukas0610
main: at.lukasberger.bukkit.pvp.PvP
website: http://lukasberger.at
description: The new PvP-Plugin - Completely rewritten - Faster, Better and Faster

depend: [ WorldEdit ]

commands:
  pvp:
    description: The base command for the PvP-Plugin
    usage: /pvp [sub-command] [arguments...]
